FROM ubuntu:23.04

WORKDIR /app

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get clean && apt-get update --allow-insecure-repositories
RUN apt-get install build-essential tzdata vim --no-install-recommends --allow-unauthenticated -y

ENV TZ=Asia/Shanghai
